config/routes.rb
Rails.application.routes.draw do
  root 'polls#index'
  post '/vote' => 'polls#vote', as: :vote
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :poll_options
end

app/models/poll_option.rb
class PollOption < ApplicationRecord
  belongs_to :poll
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @poll = Poll.where(finished_at: nil).last
    @poll_options = @poll.poll_options.order :name
  end

  def vote
    @poll_option = PollOption.find params[:poll_option_id]
    @poll_option.increment! :votes

    respond_to do |format|
      format.turbo_stream { render :vote }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VOTACAOBbb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/polls/_poll.html.erb
<div id="poll-container">
  <h1 class="text-4xl font-bold mb-8">
    Paredao das linguagens: Vote para eliminar.
    <%= @poll_options.pluck(:name).to_sentence(last_word_connector: ' ou ') %>
  </h1>

  <div class="flex flex-col gap-4 w-100">
    <% @poll_options.each do |item| %>
      <%= button_to vote_url, method: :post, class: 'flex-grow flex items-center border border-gray-600 text-left p-4', form_class: 'w-100 flex', params: { poll_option_id: item.id } do %>
        <h2 class="text-slate-800 text-2xl font-bold flex-grow"><%= item.name %></h2>
        <%= image_tag item.photo, class: 'h-16 w-16 object-contain' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/polls/index.html.erb
<%= render 'poll' %>

app/views/polls/vote.turbo_stream.erb
<%= turbo_stream.replace 'poll-container' do %>
  <div id="poll-container">
    <div class="flex items center p-4 mb-8">
      <div class="flex-grow">
        <p class="font-semibold text-slate-700">Voce votou em</p>
        <p class="text-2xl font-bold"><%= @poll_option.name %></p>      
      </div>
      <%= image_tag @poll_option.photo, class: 'h-16 w-16 object-contain' %>
    </div>

    <%= link_to 'Votar novamente', root_path, class: 'block text-center p-3 text-white bg-violet-800' %>
  </div>
<% end %>